### ISSUE TITLE
No horizontal margins on mobile

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/neve-fse#101]
### Description

By default, we don't have any horizontal margins for Archives and Singles, on mobile
Blog - https://vertis.d.pr/i/kmWuMK
Single Post - https://vertis.d.pr/i/RQDAJ2
Sample page in [Neve FSE](https://vertis.d.pr/i/02rPQR) vs [2024](https://vertis.d.pr/i/jWV9OA)

Reported here - https://wordpress.org/support/topic/editing-mobile-view-only/

### Step-by-step reproduction instructions

1. Install Neve FSE
2. Check the mentioned templates on mobile

### Screenshots, screen recording, code snippet or Help Scout ticket

Blog - https://vertis.d.pr/i/kmWuMK
Single Post - https://vertis.d.pr/i/RQDAJ2
Sample page in [Neve FSE](https://vertis.d.pr/i/02rPQR) vs [2024](https://vertis.d.pr/i/jWV9OA)

### Environment info

Neve FSE 1.0.6 / WordPress 6.4.1 / PHP 8.0

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@JohnPixle I tried to see what's wrong here but it's tricky. I wanted to ask you why Neve FSE styles are different from Raft with padding zero being used in various places, like parent containers of frontpage and header. Was this a conscious choice with some reason behind it?

**Comment by irinelenache** [comment]
+1 https://wordpress.org/support/topic/problem-with-padding/#post-17375545
