### ISSUE TITLE
Neve FSE child theme

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/neve-fse#109]
### What problem does this address?

There are users who want to use a child theme with Neve FSE (and other FSE themes) in order to make some personal customizations, and we can offer only guides on how to achieve this.

Reported here - https://wordpress.org/support/topic/child-theme-problem-33/#post-17380947 (1 star review)

### What is your proposed solution?

It would be great to have a ready-to-use child theme as we have for Neve or Hestia.

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by irinelenache** [comment]
Thank you for checking @JohnPixle!

As a note here, the child themes are pretty often asked for in the support forums for all our FSE themes. If indeed it's easy work, it would be great if we could do the same at least for Raft also.

**Comment by HardeepAsrani** [comment]
Hey @irinelenache,

I've attached the child theme here. You can upload it wherever we have these, or let me know and I can do it.

Personally, I don't think you really need a child theme for FSE themes as all the information can really be changed from the Site Editor but if the user wants it then why not. If we want to make one for raft, we just need to replace all the instance where we use `neve-fse` or `neve_fse` in this file with `raft.`

It's just two files with about 10 lines of text.

[neve-fse-child.zip](https://github.com/Codeinwp/neve-fse/files/14169939/neve-fse-child.zip)

**Comment by HardeepAsrani** [comment]
@JohnPixle It seems to be an issue with WP/MacOS: https://diviextended.com/incompatible-archive-error-in-wordpress/

For images, I suppose we can just include the same image as the screenshot of the parent theme?

**Comment by HardeepAsrani** [comment]
Apart from the zip issue, child themes look to be coded properly.

**Comment by HardeepAsrani** [comment]
@JohnPixle I did that but it seems Block Themes aren't 100% compatible with child themes. If you create a child theme for a block theme, some templates like Header/Footer are missing on the homepage as Block Editor still uses active theme slug for looking and doesn't fallback to parent theme when a child theme is active. For now, I'll recommend when don't ship child themes and ask users to use Site Editor for making changes.
