### ISSUE TITLE
NPS score popup appearing after theme activation

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#116]
Hey @HardeepAsrani !

I was just checking Neve FSE in a tasteWP instance, and the NPS score popup appeared right away after the theme activation.

Here's a screenshot from the themes page

![Screenshot 2024-02-28 at 10 37 01 PM](https://github.com/Codeinwp/neve-fse/assets/4193672/572339f9-0556-4e24-b72d-b1c0bf0fbd4c)

I also noticed that we have a very [high drop-off](https://app.formbricks.com/environments/clr7hcws7et2g8up0tpz8u8es/surveys/clr7hdihfet3q8up0jc0o69kx/summary) in the interaction, maybe this is because of the incorrect timing?

Perhaps you can take a look if you can replicate it.

Thanks!

**Comment by HardeepAsrani** [comment]
After some testing, it happens when sometimes theme is not installed directly from repository and the install_time is still not set when the first page load happens.

**Comment by HardeepAsrani** [comment]
@JohnPixle All have been released. 🚀
