### ISSUE TITLE
New Template Part for Page Title Area

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#14]
@preda-bogdan 
Had a meeting today with Mihai, and we decided that it would make sense to try out a template part where the user can swap between Page Title Area layouts.

Essentially, users will be able to set up pre-configured Page title sections, in a way that is aligned to Neve's existing options.

[This is a collection](https://fse-neve.vertisite.cloud/page-title/) of different Page Headers that we will convert to template parts:

I need your help  with registering the Template parts. We need something like this:

```
{
      "name": "page_title",
      "title": "Page Title",
      "area": "page title"
    },
    {
      "name": "page_title-1",
      "title": "Page Title - Default",
      "area": "page title"
    },
    {
      "name": "page_title-2",
      "title": "Page Title with background",
      "area": "page title"
    },
    {
      "name": "page_title-3",
      "title": "Page Title with background",
      "area": "page title"
    },
    {
      "name": "page_title-4",
      "title": "Page Title Cover",
      "area": "page title"
    },
    {
      "name": "page_title-5",
      "title": "Page Title Cover Boxed",
      "area": "page title"
    },
```
Can you create register this? we will build the actual layouts in the emo, and then move the code to the theme.

Let me know if it makes sense and / or if you need any clarifications.

**Comment by preda-bogdan** [comment]
@JohnPixle I've registered a new section for the Page Title and added the Page Title parts that you referenced. When you have some time, please have a look over the linked PR and let me know if it solves this issue or if there are other changes required.

Thank you!
