### ISSUE TITLE
Fatal error message when activating plugin other than Otter

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/neve-fse#147]
### Description

When you have Neve FSE, and try to activate another plugin other than Otter, you get this message "Plugin could not be activated because it triggered a fatal error."

![Annotation on 2024-09-04 at 13-01-00](https://github.com/user-attachments/assets/6838e238-7cc6-4065-8aaf-50f0136a3f35)

### Step-by-step reproduction instructions

1. Install Neve FSE
2. Try to install and activate a plugin, other than Otter -> the message  "Plugin could not be activated because it triggered a fatal error." appears even though the plugin gets activated.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://wordpress.org/support/topic/error-when-activating-plugin-49/

The user suggested to change this:

`add_action( 'activated_plugin', 'after_otter_activation' );`

to:
`add_action( 'activated_plugin', array( $this, 'after_otter_activation' ) );`

https://vertis.d.pr/v/CLJKaO

### Is the issue you are reporting a regression

No

**Comment by selul** [comment]
@vytisbulkevicius let's prioritize this.

**Comment by HardeepAsrani** [comment]
Thank you @rodica-andronache, I've fixed it here and made a release: https://github.com/Codeinwp/neve-fse/pull/148
