### ISSUE TITLE
Improve Style Variation Previews

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#16]
I was wondering if we have any control over the colors of the generated thumbnail of each style variation:

![Screenshot 2023-04-03 at 11 43 03 AM](https://user-images.githubusercontent.com/4193672/230877443-abd92220-6878-474d-852e-9ce787bb157a.png)

Currently these do not make much sense. I think it would be good to display in the two circles the `Foreground` and `Accent` colors.
Would it be possible @preda-bogdan ?

**Comment by preda-bogdan** [comment]
@JohnPixle Even if it were possible to target those from inside the theme they would still not display the same inside Wordpress.org Preview, causing more confusion. This is the way they choose to display the variations. I don't think we can do much about this.
