### ISSUE TITLE
Patterns and Image Assets

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#20]
Hey @preda-bogdan, some updates for the patterns, I think we can start with this too.

### Pattern HTMLs
During the last days I worked on finalising the patterns, and collected all of them as individual HTMLs into a ZIP.

[Patterns.zip](https://github.com/Codeinwp/neve-fse/files/11261687/Patterns.zip)

Please note that for your convenience, each html file includes an area like this at the top:

```
slug: Page Title - Simple
title: page-title-simple
categories: Neve FSE
keywords: Page Title, Post title
```

### Image Assets

One thing we must do before registering the patterns, is to replace the existing image assets in the theme files in order for the image slugs to match.
[Image_Assets.zip](https://github.com/Codeinwp/neve-fse/files/11261719/Image_Assets.zip)

Please do not hesitate to ping me at anytime if you need any clarifications, or have any questions.

**Comment by preda-bogdan** [comment]
Hey @JohnPixle, thank you for your input, I've removed the legacy patterns and images and replaced the hero pattern.

The changes should be visible on the linked PR.

**Comment by preda-bogdan** [comment]
@JohnPixle I've added the missing front-page patterns and changed the front page. All changes are on the linked PR. Please confirm that everything is working as expected, and if there are no more changes let me know so that I can close this issue and #17 and move forward.

Thank you!
