### ISSUE TITLE
Add Site title to default Header

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#22]
@mghenciu I did a quick test of the latest build on a fresh taste instance, and looks like we'll have some issues when there is not a logo defined. 

![Screenshot 2023-04-19 at 1 34 22 PM](https://user-images.githubusercontent.com/4193672/233049137-65d29f04-47ca-4dbb-b533-3cd37749c0b6.png)

My suggestion would be that for the Default Header, to include the Site Title next to the Site logo.
Do you think you can revise the Header variation code?

**Comment by mghenciu** [comment]
Thanks for reporting this, John.
I've made the changes in [this commit](https://github.com/Codeinwp/neve-fse/pull/8/commits/c35ebc3abc612b398bbd639689079af2e7295bff) and it should be good now (attached an example from the latest build).

![image](https://user-images.githubusercontent.com/52494172/233067227-4bed85af-d507-4656-8ab1-e1058428c2b2.png)

___

![Screenshot 2023-04-19 at 14 56 09](https://user-images.githubusercontent.com/52494172/233067615-c5e3fba0-2a44-480f-846c-fc51b5408ac3.png)
