### ISSUE TITLE
Secondary Buttons issue

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#23]
Hey @preda-bogdan, there looks to be an issue with the secondary buttons (outline style)

When using a secondary button, and attempting to change the text Color, the border should also inherit the color. 

Currently, it looks like the color of the border is inheriting the `ti-foreground` color, and does not inherit the specified color from the UI (as expected)

![Screenshot 2023-04-19 at 2 05 29 PM](https://user-images.githubusercontent.com/4193672/233056231-e41ebdca-36af-45ab-a89c-ce930c278bab.png)
![Screenshot 2023-04-19 at 2 06 06 PM](https://user-images.githubusercontent.com/4193672/233056264-11060fa4-71c3-4ce3-8557-da29c4984117.png)

Think we can do something about it? I am not sure what happened here, since it was working as expected in our other FSE themes.

Thanks! Let me know if you need more clarifications.

**Comment by preda-bogdan** [comment]
@JohnPixle fixed this issue here: https://github.com/Codeinwp/neve-fse/pull/21
It will now inherit the button text color for the border.

Let me know if this is resolved.
