### ISSUE TITLE
Feat: Design and Styles for new Neve FSE

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/neve-fse#3]
@Codeinwp/design-team 
You can use this issue to add your designs and ideas and keep everything related to the design and styles here for easy reference, prior to implementing this.

**Comment by mghenciu** [comment]
@JohnPixle , I started building some variations for the Footer and Single Post pages. One thing I noticed while doing this, is that there may some challenges for the Archive and Single pages. Basically that for the Footers and Headers, those templates can be easily added on a page **via the Block inserter**. But let's say we build 3 Single Post variations, **how would a user switch between them in an easy way?** for example if he wants now all his Single posts to look like variation 3.

Right now, the way to do this is by copying content of a variation in the Main Template, but this doesn't sounds like a good approach. 

I am asking this now, so we don't invest too much in variations that may be hard to configure and use.

___
After more digging, I see that it's possible to Create Custom Templates, and using Edit on Posts and Pages -> assign a Template:

![Screenshot 2023-03-31 at 17 47 40](https://user-images.githubusercontent.com/52494172/229153957-8b14df3c-44a0-4cee-89a0-0cfe1e96b199.png)
![Screenshot 2023-03-31 at 17 48 11](https://user-images.githubusercontent.com/52494172/229153965-174c95ce-29bd-4799-9303-8e8483ec2185.png)


For me it looks more like a hacky way of doing things, as it's not even in the FSE menu. But if that's all we have, we'll have to take it.
I was imagining that it would work something dropdown, so in case an user has more Single Post templates, he can easily choose what template to use as main Single Post.

**Comment by mghenciu** [comment]
If changing templates globally is too complicated from a user perspective **now**, what we can do John, is to **have only 1 variation for Single Post and 1 for Archive.** So a total of 4 templates (2 default + 2 variations).

Later, when Core will have a more intuitive way of switching Variations -> we can add more templates.

**Comment by preda-bogdan** [comment]
> @preda-bogdan
> 
> @preda-bogdan For these stepper here, can we provide the default values of each step? ![Screenshot 2023-04-03 at 10 30 06 AM](https://user-images.githubusercontent.com/4193672/229441062-12f5d057-1174-47f0-8b44-ef920be03932.png)

@JohnPixle Can you be more specific about where that section is located?

**Comment by preda-bogdan** [comment]
@JohnPixle Yes, we can also define `general` sections that can be inside the `parts` folder.
