### ISSUE TITLE
Sticky Header option not being respected

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/neve-fse#30]
### Description

The WordPress Sticky option for Header is not being respected.

### Step-by-step reproduction instructions

1. Go Site Editor > Header Template Part > Group > Position
2. Set the Position to sticky.
3. The class `is-position-sticky` is added but the Element does not stick to the top.

I think we can improve this since the expected behavior is for that element to stick to the top of the window as specified inside the description.

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="2205" alt="image" src="https://github.com/Codeinwp/neve-fse/assets/23024731/def8b501-5460-4169-8278-fecb10069cfa">

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment]
@preda-bogdan Tested and the sticky option is working fine now 🚀
