### ISSUE TITLE
Looks into how Patterns are assigned in Categories

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/neve-fse#33]
### What problem does this address?

As discussed in the Meeting, it may be a good idea to research how patterns are categories in the inserter popup. 
Since right now we have a separate tab (for example Neve FSE Patterns, Otter Patterns) - but most of those could also belong in other categories.

### What is your proposed solution?

What we can do is keep the current approach, for consistency and easy of use (all Patterns from a product have their Tab) - **but also look into how we can include those in different categories.** For example let's say in Neve FSE Patterns we have Page headers, those should also be added under the Headers Tab. And so on for other categories.

This needs more research on how we can implement it, maybe with keywords.

**Comment by ineagu** [comment]
I think we can consider creating new categories as well like: Before Header category or Featured in patterns or Contact form patterns,
