### ISSUE TITLE
Image Assets and Licensing

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#4]
Starting to note down the images we used for the demo, for when we will submit to the repo.

https://negativespace.co/man-writing-notepad/
https://negativespace.co/woman-browsing-smartphone/
https://www.rawpixel.com/image/5928246/man-using-laptop-free-public-domain-cc0-photo
https://www.rawpixel.com/image/5920695/photo-image-book-public-domain-technology
https://www.rawpixel.com/image/5926325/photo-image-background-public-domain-technology
Hero Section: https://pxhere.com/en/photo/13688
Testimonial 1: https://stocksnap.io/photo/woman-business-LERRJPTMHP
Testimonial 2: https://stocksnap.io/photo/business-woman-FPQIEQBMPA
Testimonial 3: https://stocksnap.io/photo/man-interior-BXO1M5UBLM

### Additional images:
@mghenciu no rush but whenever you have the time can you help me with something:

Get the url for the hero image (i could not find it with reverse search)
and also, get the urls for the three testimonials (thanks btw, they look very good).

Feel free to edit this message and add the urls in the list above.

![neve-fse-img12](https://user-images.githubusercontent.com/4193672/236241673-332e346b-7625-4de6-beda-fecbfb997ce6.jpg)

![Screenshot 2023-05-04 at 5 41 41 PM](https://user-images.githubusercontent.com/4193672/236242313-1f6a2d8b-4452-462a-87af-84b045feacb1.png)

**Comment by mghenciu** [comment]
I've added the links in the comment above 🚀
