### ISSUE TITLE
Update doc link

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/neve-fse#42]
### Description

After you download Neve FSE, the Read Documentation button https://vertis.d.pr/i/zuWAFE links to https://docs.themeisle.com/search?query=Neve+FSE&utm_source=brevo&utm_medium=email&utm_campaign=Neve35&_ga=2.213677332.1690962744.1685651626-266967465.1677360693
which has the first two results about a child theme, not Neve FSE, which I think can be confusing.

I think it would be best to link directly to https://docs.themeisle.com/article/1774-neve-fse

**Comment by preda-bogdan** [comment]
@rodica-andronache I've updated the documentation URL that is present on the Thank You page after you download Neve FSE. Let me know if everything is working as expected now.

Thank you!

**Comment by rodica-andronache** [comment]
@preda-bogdan everything's working well 👍

**Comment by preda-bogdan** [comment]
@rodica-andronache Thank you. will close this.
