### ISSUE TITLE
Submit to w.org

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/neve-fse#44]
### What problem does this address?

@HardeepAsrani @vytisbulkevicius I am not sure here who has access, but we can submit the theme to w.org on Monday-Tuesday next week.

Let me know if you need anything.

**Comment by preda-bogdan** [comment]
I believe we also need to include back the SDK prior to submitting the theme.

**Comment by HardeepAsrani** [comment]
@preda-bogdan We can add the SDK and submit it to WPorg in the start of the next week. We can give the prepared build to Vytis who has the wporg creds.

Let us know @ineagu if anything else is required on this end.

**Comment by vytisbulkevicius** [comment]
I uploaded the theme:

Thank you for uploading Neve FSE to the WordPress Theme Directory. We’ve sent you an email verifying that we’ve received it. Feedback will be provided at https://themes.trac.wordpress.org/ticket/142887

Will keep this issue opened until it's approved.
