### ISSUE TITLE
Remove src files from build

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/neve-fse#47]
### What problem does this address?

We forgot to put the `assets/js/src` folder in the distignore and TRT has asked us to remove that during the review.

### What is your proposed solution?

Put assets/js/src in the .distignore, and release a new version with it to submit to wp.org.

**Comment by HardeepAsrani** [comment]
I've asked them to confirm if they're only talking about src: https://themes.trac.wordpress.org/ticket/142887#comment:3 - so we can make the change and wait for their response before we do another release and submit it back.

**Comment by preda-bogdan** [comment]
I added the changes to the PR with the SDK since that is the build that was submitted for review. Will also monitor their response.
