### ISSUE TITLE
Clicking on social icons from header/footer goes to an empty page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/neve-fse#48]
### Description

Clicking on the social icons from header or footer goes to an empty page, which looks weird especially in the wp.org preview where it looks like the page is loading forever.

<img width="1396" alt="Screenshot on 2023-06-19 at 17-47-44" src="https://github.com/Codeinwp/neve-fse/assets/3266155/203a62a3-09c2-49c3-9fdb-3b66a19a9e17">

### Step-by-step reproduction instructions

How it looks on wp.org: https://vertis.d.pr/v/yBMFrJ
How it looks on a local site: https://vertis.d.pr/v/jlBGpY

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@rodica-andronache Based on the code, it's set to # and same format is used by all other FSE themes. I don't think we can do anything here, correct me if I'm wrong @preda-bogdan
