### ISSUE TITLE
Enable the WP.org action for releases

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/neve-fse#51]
### What problem does this address?

Right now the release action only deploys to the store.
We need to update the action to also use the credentials for updating to WP.org.

**Comment by HardeepAsrani** [comment]
I've enabled the `SVN_THEMEISLE_USERNAME` and `SVN_THEMEISLE_PASSWORD` secrets for this repo, so all necessary secrets needed for this are available to the repo now.
