### ISSUE TITLE
Duplicate title tag when RankMath is active

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/neve-fse#53]
### Description

When the RankMath plugin is active, the title tag is duplicated in the page source.

### Step-by-step reproduction instructions

1. Install and activate Neve FSE
2. Install and activate RankMath
3. Visit the website you are testing on, check the page source, and search for the title - it appears twice

### Screenshots, screen recording, code snippet or Help Scout ticket

![neve-fse-duplicate-title](https://github.com/Codeinwp/neve-fse/assets/26867648/16d71502-0011-45a9-ba24-acd8c2062977)

Reported here: 
https://wordpress.org/support/topic/remove-the-tag-in-the/
https://secure.helpscout.net/conversation/2286660220/375645/

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
This seems to be an issue with all of our FSE themes, maybe we can remove them all at once? Seems to be due to `add_theme_support( 'title-tag' );`

**Comment by HardeepAsrani** [comment]
AFAIK, Core themes aren't using the add_theme_support in FSE themes.

**Comment by stefan-cotitosu** [comment]
https://secure.helpscout.net/conversation/2283536755/374459/

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani, thank you for sharing a potential solution.

I provided it to the customer and it doesn't work. Also tested it myself and it doesn't work.

Can you please help with another code snippet?

**Comment by HardeepAsrani** [comment]
@stefan-cotitosu That wasn't for the support. We have that code in Theme and we need to remove for it to work. Sorry if my commend was confusing.

**Comment by stefan-cotitosu** [comment]
Ok, sorry for that; my bad, didn't read it carefully.
