### ISSUE TITLE
Enable 'Inner blocks use content width' for the main Groups

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/neve-fse#54]
### Description

As discussed on [Slack](https://vertistudio.slack.com/archives/C04CP8FPNNA/p1688719175022669), the sections on each page are imported as a Main Group, but this makes it look like the whole page has a Padding.

In order to mitigate this, we need to enable the **Inner blocks use content width** for the main groups, which will make the Padding invisible in the Editor.

### Step-by-step reproduction instructions

1. Create a fresh instance
2. Install Neve FSE 1.0.3
3. Open the Front Page in edit mode and notice the visible Padding in the Editor

### Screenshots, screen recording, code snippet or Help Scout ticket

![Screenshot 2023-07-07 at 11 37 07](https://github.com/Codeinwp/neve-fse/assets/52494172/d39feb75-68b0-433f-bdd8-01febf95e3dc)
![Screenshot 2023-07-07 at 11 34 09](https://github.com/Codeinwp/neve-fse/assets/52494172/f88f55b5-3ccb-42b2-b12e-b455321b941a)

![Screenshot 2023-07-07 at 11 31 57](https://github.com/Codeinwp/neve-fse/assets/52494172/bdb8fe0e-3431-4e48-8f32-994f0731698e)

___

The setting that needs to be enabled:
![image](https://github.com/Codeinwp/neve-fse/assets/52494172/fc09b4fe-02c4-495c-b670-f1f22ef61ecd)

### Is the issue you are reporting a regression

No

**Comment by mghenciu** [comment]
@JohnPixle , I did the required changes in this [PR](https://github.com/Codeinwp/neve-fse/pull/56).
Tested a few times and the padding issue looks to be fixed.

When you have some time, to review it @preda-bogdan 🚀

**Comment by mghenciu** [comment]
As an update here, the issue looks to be more dev oriented and complex than just enabling the Inner blocks toggle; that's why we put it On Hold in the Design Board.

As next steps, we need to review a bit the things in terms of default theme padding and spacing, plus make sure we are compliant with the main group required by wordpress; and of course that things work as expected in any FSE context.

We'll need some dev help here, @HardeepAsrani .
I've added more details about the challenges, [in this PR](https://github.com/Codeinwp/neve-fse/pull/56).
___
Also we wanted to ask how would this changes affect the existing sites? for example let's say we update the color for a section, or we change some icons, etc. -> **when released, would this changes also apply on the existing sites that use Neve FSE?**

**Comment by mghenciu** [comment]
@HardeepAsrani , pleased don't forget about this one - when you get some time.
Should I add it in the Backlog or To Do?

**Comment by HardeepAsrani** [comment]
@preda-bogdan Can you look at if you have the time?

> when released, would this changes also apply on the existing sites that use Neve FSE?

Looking at the changes, I think they won't affect existing sites as we only change template content. Correct me if I'm wrong, Bogdan?

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu Can you look into this when you have some time? Mihai has already made a PR related to this.

**Comment by mghenciu** [comment]
Just fyi: [it looks like the issue I was mentioning here](https://github.com/Codeinwp/neve-fse/pull/56#issuecomment-1634278632), regarding previewing Styles - **this doesn't happen anymore on 6.3.**

**Comment by cristian-ungureanu** [comment]
@mghenciu @HardeepAsrani the reason for that padding inside the editor is actually this code: 

https://github.com/Codeinwp/neve-fse/blob/main/assets/css/src/common/_generic.scss#L45-L55

Bogdan started from Fork's style, we have the same issue there. After digging a while, here's what I've found:

The style was added because in ( not that ) older WP versions ( eg. WP 6.1 ) we had this issue: https://vertis.d.pr/v/VLFBl1. After digging some more,  I found out that removing this line here https://github.com/Codeinwp/neve-fse/blob/main/theme.json#L14 fixes both the current issue that we have now, and the fix even works on WP 6.1, allowing us to also remove that padding style. There's no need to change the templates.

As I'm not quite an expert with FSE themes, please let me know if you can think of a downside to the solution I've mentioned.

**Comment by mghenciu** [comment]
Thank you for the in-depth research, Cristi.
Also, not an expert in FSE themes :)) but I would we can take inspiration from Core FSE themes: 2023 and 2022, and Frost (which are available on Github).

If this fix is working without doing any templates changes -> that's even better 🚀

**Comment by cristian-ungureanu** [comment]
Thanks, Mihai for the feedback! I actually did check WP FSE themes and none of them are using the `outer` property, nor the padding that we're adding.
