### ISSUE TITLE
Reduce button padding on mobile viewport

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#55]
Currently the buttons in Neve FSE have a generous padding (16px 40px). However, in Mobile this results in some issues with button not staying inline.

![Screenshot 2023-07-12 at 12 25 27 PM](https://github.com/Codeinwp/neve-fse/assets/4193672/374dfd0d-00be-416f-9b3c-04a6ec8ac292)

I was wondering, if for mobile viewport we can have the buttons set to 16px padding (all sides).
Please note that this should also apply for the` is-style-outline` button

Hopefully we will be able to have the buttons inline on mobile.

![Screenshot 2023-07-12 at 12 28 55 PM](https://github.com/Codeinwp/neve-fse/assets/4193672/030fa33e-7e1f-4106-849a-a3bda190531d)

@HardeepAsrani Let me know your thoughts, and happy to help with clarifications and more info!
Looping-in @mghenciu for awareness.

**Comment by HardeepAsrani** [comment]
@JohnPixle I don't mind really, it's a purely design decision so I'd leave it to you and how you want to proceed with it. 😄

**Comment by HardeepAsrani** [comment]
@JohnPixle It's added here: https://github.com/Codeinwp/neve-fse/blob/f01d8627a32f5b8ddd8d1ef05835d8070448dcde/assets/css/src/common/_generic.scss#L76

You can use SASS to have a @media selector.

**Comment by HardeepAsrani** [comment]
@JohnPixle My bad. 😄 Here's an example of how Bogdan is doing this in another file: https://github.com/Codeinwp/neve-fse/blob/f01d8627a32f5b8ddd8d1ef05835d8070448dcde/assets/css/src/welcome-notice.scss#L1-L18

This should also help: https://sass-lang.com/documentation/at-rules/css/

**Comment by mghenciu** [comment]
I've made some changes in this [PR](https://github.com/Codeinwp/neve-fse/pull/60), @JohnPixle , and used 16px 20px, which should be fine even for smaller Mobile Devices. Let me know if this looks and works as expected.

___

@HardeepAsrani , I've tried using the DRY principle in CSS, not sure if I managed to achieve perfection :)

**Comment by mghenciu** [comment]
I'll move this to testing, since Bogdan and John reviewed the changes.
