### ISSUE TITLE
WordPress 6.3 compatibility

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/neve-fse#62]
**Neve FSE** was tested using WordPress 6.3 RC2 and no issues were found, so after the release (aprox. Aug 8) we can note that the product is compatible with the latest wp version 🚀

**Comment by HardeepAsrani** [comment]
Closes in https://github.com/Codeinwp/neve-fse/commit/dc501c7ace5c8f0f5b8eab2b9ef09c91b653859f
