### ISSUE TITLE
Remove Survey Link & fix multiple notices appearing at once

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#69]
As discussed, we will pause the Typeform survey for now, and re-evaluate after a year, so we need to remove the banner altogether from the dashboard. 

**Edit by Hardeep:** Please also refer to the issue mentioned in the [first comment](https://github.com/Codeinwp/neve-fse/issues/69#issuecomment-1687692898), which happens if you have a theme installed for a while (you can change the option to set the install time to a past date)

We can make sure:

- The survey link is disabled.
- Marketing notifications don't appear together
- The Neve FSE promotional message on the Themes screen must not appear if the user is already using Neve FSE.

**Comment by mghenciu** [comment]
Sounds good!

What I was thinking is to establish a general logic in showing this type of informative Toasts:
- **do not show multiple Informative/Marketing** notices at once in any Product. 
- we can show multiple notices, if those are about Critical Errors - or other things non Marketing/Informative
- maybe a shuffle mechanism would make sense. For example let's say we show the Do you enjoy Neve FSE in week 1. And the user doesn't do anything with it, doesn't dismiss it or else. After X time -> we can shuffle and show the Take the survey notice - having this way only 1 notice visible at a time. 

But would love to have someone's else involved in testing the logic, to make sure we avoid such cases with stacking.

**Comment by HardeepAsrani** [comment]
I think we can go with the first approach and not show multiple notices from marketing/info at once, while not doing the same for things like License notices.

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani what about the welcome notice?
![Screenshot 2023-08-28 at 17 50 49](https://github.com/Codeinwp/neve-fse/assets/9929553/4a9cd06b-6d4c-46b7-a2aa-fc396e0f0b38)

Should this be included in the marketing notices that should be visible randomly?

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu  Yea, unless something is a required action, for example License activation, we no two notices should appear at once.

**Comment by HardeepAsrani** [comment]
> We need to change the notifications from inside the theme and use the filter mentioned above.

For the second notice, I'm guessing we can keep it like this as it appears post-theme install, so usually, it should go away instantly. Maybe we can have some filter that tells SDK not to show other messages if one is being enabled from the theme?

For the:

> We need to change [the notice made in JS](https://github.com/Codeinwp/themeisle-sdk/blob/master/assets/js/src/neve-fse.js) and add it as a Notification, not as a Promotion. I'm not exactly sure where to do this. I could move it inside the theme and use [themeisle_sdk_registered_notifications](https://github.com/Codeinwp/themeisle-sdk/blob/master/src/Modules/Notification.php#L464) filter but there will be some new strings that will be added. Or we can let that one appear in parallel with the others.

We have other promotions that might be triggered at various times, I'm still guessing something along the lines to show so more than one notice/promotion at a time.

Thoughts @Codeinwp/platformsops @Codeinwp/marketing?

**Comment by atikurTonmoy** [comment]
We may prioritize the display of messages based on user actions and their stage in the user journey:

- New Users (Day 1-3): Show a welcome message to introduce them to the [Neve FSE theme](https://prnt.sc/NNSPLp283gSk), guiding them through the features.
- Day 4-7: Transition to a notice encouraging users to opt into anonymous data tracking with [this notice](https://prnt.sc/mQlpEw9TlHun).
- Existing Users (7+ Days): Prompt them to share [experience and feedback](https://prnt.sc/nEcWo6gqrAEL).
- Upon Activation: Keep the [Otter blocks promotional notice](https://prnt.sc/x1DxQrIvBtez) right after theme activation (as same as it is).

By utilizing behavioral triggers or timers, we can present notices at the most relevant times. This will help us cap the frequency of notices, ensuring users are not overwhelmed.

Note: We may need to change the texts of the banners to make them more relevant and contextually accurate.

**Comment by abaicus** [comment]
@HardeepAsrani, I think the initial welcome notice recommending Otter is fine as-is. The bigger issue is that the theme recommends itself. 

From what I understand, there's a clash between promotions and notices, which especially affects this theme because we don't [condition the notice](https://github.com/Codeinwp/themeisle-sdk/blob/master/src/Modules/Promotions.php#L354) based on the theme being active/installed or not.

The other notices showcased in this issue are related to asking for reviews or tracking access, and what @atikurTonmoy shared as a timeline for how we should display sounds excellent to me.

**Comment by HardeepAsrani** [comment]
Thank you @atikurTonmoy for the feedback, my only concern with setting an lower & upper limit with notices is the cases where the user doesn't open their WP dashboard in that particular timeframe and miss out on notices. Let me know what you think.

**Comment by atikurTonmoy** [comment]
That's a valid concern, @HardeepAsrani. How about we only initiate the timer for each notice after the user's first login within a specific timeframe? For example, if we have a notice set to appear from day 1 to 3, the timer starts only when the user logs in on what becomes their "new" day 1. If they log in after a week, then that's when their 'day 1' starts, and the notice will be displayed until their 'day 3'. This ensures they don't miss any critical notices, even if they don't regularly check the dashboard.

**Comment by HardeepAsrani** [comment]
@atikurTonmoy That does sound a bit complicated to include in the current workflow. I'll suggest we can go with a simple approach for this issue and discuss this separately as I do like this approach and should be able to make the user experience. Let me know your thoughts.

**Comment by atikurTonmoy** [comment]
Sure, @HardeepAsrani. We may proceed with the simpler approach for now to address the immediate issue. Thank you!

**Comment by cristian-ungureanu** [comment]
Hey @HardeepAsrani, I'm going to summarize what we've talked about so far, but please have a look and correct me if I'm wrong:
1. Disable the survey by commenting on the code so we can enable it later.
2. Condition the notice so the Neve FSE promotion does not appear while having Neve FSE enabled.
3. Everything else stays the same, including the welcome notice, asking for a review notice, and the data tracking notice.

Let me know if I'm correct and if there is anything else.

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu Yes, one more thing to add:

- Do not show any other message on Themes page if Neve FSE promo is enabled.
