### ISSUE TITLE
Getting a fatal error with the latest version.

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#7]
@preda-bogdan I am not sure if it has to do with some of the minor changes I did, but I am getting a fatal error at the demo, when I am trying to update the theme with the latest build.

No rush, I am working with the previous version for now.

![Screenshot 2023-04-04 at 7 07 23 PM](https://user-images.githubusercontent.com/4193672/229852292-ac3f3703-c3e3-441f-99ad-46d5998d0113.png)

**Comment by preda-bogdan** [comment]
@JohnPixle I've created a PR here that you can use. You can add your changes to the `feat/neve_fse_design` branch and when you push the build will be updated on the PR. You can use that to download and update the theme. We can also discuss changes there. If you require any syncing or other support on this let me know. Thank you!

cc: @mghenciu 

Will close this issue.
