### ISSUE TITLE
Test potential improvements from the WP 6.3 release

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/neve-fse#72]
### What problem does this address?

The QA team already did tested all of our products with the upcoming WP 6.3 release, but we'll need to do a small UIX audit, and see if we can improve some things in the Neve FSE context.

Maybe with those changes, there is space for improving the Neve Layout Templates section, reusable template or other things that we have.

### What is your proposed solution?

Do a short UIX review of the news features, assess if we need to do some changes and look for potential improvements from this release.  

### Will this feature require documentation? (Optional)

None

**Comment by mghenciu** [comment]
One thing I noticed so far @JohnPixle , while checking the new 6.3 release - is that we have the Patterns in 2 folder/categories. While the other popular themes use specific categories.

<details><summary>Neve</summary>

![Screenshot 2023-08-25 at 15 02 51](https://github.com/Codeinwp/neve-fse/assets/52494172/03771800-c345-4ac2-ac5f-037198ff42d9)


</details>


<details><summary>Spectra & Ollie</summary>
![Screenshot 2023-08-25 at 15 03 29](https://github.com/Codeinwp/neve-fse/assets/52494172/3c359b73-4284-4504-a96e-31dc42089725)

![Screenshot 2023-08-25 at 15 03 54](https://github.com/Codeinwp/neve-fse/assets/52494172/be6402de-9d00-4ed3-9733-e2cdebe6f535)


</details>

This applies for both the Patterns Tab, but also when doing the insertion in editor.

In a way, it makes sense to have all Neve grouped in one place, but it's a bit harder to find what you need based on a category. 

Let me know your thoughts, when you have some time.

**Comment by HardeepAsrani** [comment]
Once you're done with the testing, can you let me know of all the actionable items from the discussion? Thanks.

**Comment by mghenciu** [comment]
@JohnPixle , I've gather the ideas so far in Notion >> https://www.notion.so/themeisle/6-3-Update-7ff91eae573145d18b10487196dbca48?pvs=4

And we can talk more about it there/on Slack.

I think for now we should be good, have a focus on improving the usage of Neve FSE Patterns & Layout, especially since we plan to have even more patterns; improve the styles.


____

And with the new 2024 theme, we'll probably have a better idea how will Core approach this idea of managing Patterns, full Page Patterns/layouts.

**Comment by mghenciu** [comment]
> I dont think there is anything else to discuss apart from patterns and pattern folders, right?

Yes, nothing else.
Probably it would make sense to **look at 6.4 from this point.**
