### ISSUE TITLE
Organise theme patterns in categories

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#89]
@mghenciu I am creating this issue to start a discussion. For now I am migrating the content from our Notion. Let's follow up on the discussion here, and we can update this original post with the final conclusions.

### Context 
So far in our FSE themes we have been adding all our theme patterns to a dedicated folder. For example in Neve FSE, we have `Neve FSE Patterns`, where the user can find all the patterns related to the theme.

The logic behind that was to provide a central location for the user to find and use theme-specific patterns, instead of them being mixed / diluted in other folders with core-provided patterns (for which the layout system was not consistent with how our theme was built.

Following the growing consensus in the theme community and the latest core versions, we can now provide a more consistent experience and ship only theme patterns, while removing the core ones. Additionally, our theme patterns will be organised in semantically named folders.

### Objectives

- [ ]  Remove the core patterns from pattern library
- [ ]  Distribute Neve Patterns into categories (folder suggestions below)
- [ ]  Remove `Neve FSE Patterns` folder (check with dev for fallback concerns)
- [ ]  Rename `Neve FSE Layouts` folder into `Pages` (discussion is ongoing)
- [ ]  Check with the Dev Team if we need to have hard limit for how many patterns we add

### Categories

- **Headers**: *contains various navigations*
- **Hero**: *the main section after the Nav. Usually it’s wide, and acts as a banner.*
- **Features**: used to present services/features
- **Content**: mainly generic text content with images (suggested)
- **FAQ**
- **Team**
- **Pricing**
- **Call To Action**
- **Testimonials**
- **Client logos**
- **Single Post**
- **Archives**
- **Footers**
- **Post Loops / related posts**
- **Pages**

  - RSVP
  - Contact
  - Coming Soon
  - Portfolio
  - Portfolio Single
  - Landing Page
  - About

### Other
- The structure in inspired by Core themes (including 2024) and other popular FSE Themes.Next step will be to agree on these categories and make sure we have at least 4 pieces in each of them.Regarding the effort, I think we have a lot of patterns that we can reuse
- These changes will be applied to our other FSE themes in upcoming releases, but would be good to test this with Neve FSE first.
- This issue is also related to this one: #33

**Comment by mghenciu** [comment]
Thank you, John!

One thing I realised now, is that our Patterns are just a bit different depending on the FSE theme. So in order to make this approach fit all our teams, I think **we should think about categories that will apply to all our FSE themes** - and have maybe (only) one distinct category/pattern type for each theme separately. 

For example in case of Jaxon, the distinct category could be something ecommerce related, while for Fork - it could be Portfolio.

Let me know what you guys think, about using 1 model - fits all; or if you think we should approach this differently across themes.

**Comment by HardeepAsrani** [comment]
Hey @JohnPixle,

I think it's a good idea to categorize patterns, I just have a just one questions:

>  Rename Neve FSE Layouts folder into Pages (discussion is ongoing)
> Also, might need to confirm if by changing folder structure there will be any issues with the current onboarding of Neve users.

I'm unable to follow this one, can you give me more information here?
