### ISSUE TITLE
Add a secondary accent color in our palette

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#92]
### What problem does this address?

Currently Neve FSE and all our FSE themes make use of a single - primary -  accent color. While this has served us well, adding a secondary accent color opens the door for more design possibilities such as:

- Working with gradients while staying consistent with the brand colors
- Allowing to set a theme color on SVG icons (through a gradient hack that @mghenciu discovered).
- Extra flexibility with one more theme color slot in the palette (both for us when building patterns and layouts, as well as the users)
- General alignment with upcoming core themes

**Duotone / gradient concepts for hero:**

![Frame 104](https://github.com/Codeinwp/neve-fse/assets/4193672/3f852f6a-6b29-4bcf-a7c6-eded0f6869fb)

**Theme style consistent colors in icons**

![Frame 1042](https://github.com/Codeinwp/neve-fse/assets/4193672/299eb09a-94bd-45f5-a75b-f8ffe04a7362)

### Existing Setup

![Screenshot 2023-10-11 at 11 33 48 AM](https://github.com/Codeinwp/neve-fse/assets/4193672/8ef0339c-d893-404f-a343-5a1fab150d96)

And this is how it looks in code:

``` "palette": [
        {
          "slug": "ti-bg",
          "color": "#FFFFFF",
          "name": "Background"
        },
        {
          "slug": "ti-fg",
          "color": "#1F2023",
          "name": "Foreground"
        },
        {
          "slug": "ti-accent",
          "color": "#F5AB1A",
          "name": "Accent"
        },
        {
          "slug": "ti-bg-inv",
          "color": "#14171C",
          "name": "Background Dark"
        },
        {
          "slug": "ti-bg-alt",
          "color": "#F6F6F6",
          "name": "Background Alt"
        },
        {
          "slug": "ti-fg-alt",
          "color": "#FFFFFA",
          "name": "Foreground Alt"
        }
```

### What is your proposed solution?

The solution is  to add a secondary accent color, which is close to the existing one. No other changes are needed at this point.

``` {
          "slug": "ti-accent",
          "color": "#F5AB1A",
          "name": "Primary Accent"
        },
{
          "slug": "ti-accent-secondary",
          "color": "#F5AABC",
          "name": "Secondary Accent"
        }
``` 

**Why we need to address this now?**

It would be good to have this color addition now because it will give us the opportunity to work with the extra color when we create and deliver patterns, pages and theme styles. Good to roll this in Neve FSE first, and then apply the logic to other themes.

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by mghenciu** [comment]
[Made the PR here.](https://github.com/Codeinwp/neve-fse/pull/93) Asked for a review from Hardeep.
Let me know if something else is required.

Thank you.

**Comment by mghenciu** [comment]
> @mghenciu Looks good, have you tried them as duotone values on images or images? It might be good to make sure these work well by default.

Yes, I tried with Color overlay in the Cover block + Duotone for an icon.
![image](https://github.com/Codeinwp/neve-fse/assets/52494172/c65683d1-8030-40d0-acc7-e1e7cc3d86f1)

![image](https://github.com/Codeinwp/neve-fse/assets/52494172/2ed36eb9-a164-42c1-b2f6-c3068bdbd978)


___

For duotone it's not possible to form one using Primary + Secondary, since the colors are very close. And in a Duotone context, those should be quite different (example below): 
![image](https://github.com/Codeinwp/neve-fse/assets/52494172/ee434e13-2a54-4808-bfba-d9145c0c76ef)

But I think it may work to use in duotone the Dark Color + Secondary accent.
