### ISSUE TITLE
Fix mistake in welcome message

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#94]
Hey, just spotted that we say " Meet Neve FSE from the makers of Neve FSE" in the welcome message. Shouldn't it say "...From the makers of Neve" ?

![Screenshot 2023-10-17 at 12 27 08 PM](https://github.com/Codeinwp/neve-fse/assets/4193672/6d56170a-c2a1-42ec-b6b7-313f408ff210)

I will squeeze it in the milestone if you don't have any objections @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@JohnPixle Sure, looks easy enough.

**Comment by HardeepAsrani** [comment]
@JohnPixle Looking at it, is it appearing when you are actually using Neve FSE? In that case, it should be fixed by https://github.com/Codeinwp/neve-fse/issues/69

**Comment by HardeepAsrani** [comment]
@JohnPixle It's the notice on Themes' page, right? It should be fixed by the other PR.
